server:
  context-path: /log
  port: 9009
  #tomcat:
    #uri-encoding: UTF-8
  session:
    timeout: 900

verCode: 1.1.0.1170 
envName: test
#isVerifySign:if check sign
isVerifySign: false
isAuthLogin: true
isSaveLog: true
isProduct: false
isSendMQ: true
requestLogQueueName: request_test
exceptionLogQueueName: exception_test
logQueueName: logMQ
businessQueueName: businessTestMQ

spring:  
  data:
    mongodb:
      uri: mongodb://111.231.99.72:27017/serverLogProd
  
  rabbitmq:
    host: 111.231.99.72
    port: 5672
    username: yucong
    password: wdmm224126
      

    