server:
  context-path: /log
  port: 9002
  #tomcat:
    #uri-encoding: UTF-8
  session:
    timeout: 900


# 系统环境参数配置    
env:
  verCode: 1.1.0.1170 
  envName: prod
  #isVerifySign:if check sign
  isVerifySign: false
  isAuthLogin: true
  isProduct: false
  isSendMQ: true

spring:  
  data:
    mongodb:
      # uri: mongodb://47.96.21.192:27017/serverLogTest
      uri: mongodb://xxx:xxx@47.102.126.118:27017/serverLog
  
  rabbitmq:
    host: 47.102.126.118
    port: 5672
    username: xxx
    password: xxxx
  
  # mysql配置
#  datasource:
#    url: jdbc:mysql://192.168.2.168:3306/common_service?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: develop
#    password: 123456   

    